### ISSUE TITLE
De facto jQuery dependency

### ISSUE THREAD

**Issue by jchester** [eu81273/angular.treeview#2] opened 2013-08-07 04:54 UTC
At line 63, the directive calls element.empty().:

```
62: //Rendering template.
63: element.empty().html( $compile( template )( scope ) );
```

This function isn't supplied as part of jqLite. This means that jquery needs to be included in order to use the directive.

Proposed fixes:
1. Use another technique to clear the DOM children before re-compiling, or
2. Update the documentation to explicitly state the dependency.

**Comment by eu81273** [comment] 2013-08-11 12:55
Thank you jchester!

I found out that there is no need to use empty().

html() method removes other constructs such as data and event handlers from child elements before replacing those elements with the new content.

The problem is fixed in the 0.1.2.

Thank you once more.

**Closed as completed** 2013-08-12 00:52 UTC
Labels: bug
